### PR TITLE
added event for June 2016

### PR DESCRIPTION
**Pull request by madmurdock**

### CODE REVIEW

**Comment by rprouse** [comment]
We still need to talk about talks.

Some ideas,

- MVVM
- Arduino development
- Continuous integration using AppVeyor or other services
- Reasons to reconsider C#/.NET

**Comment by bpoetz** [comment]
Thanks rob, pushed up a branch with a talk that Emily is going to give about wagtail. 

I'd say whatever you are most interested in talking about - I'd be most interested in a CI talk, but do whatever is most interesting to you.

**Comment by madmurdock** [comment]
Rob and I were planning a double-header like we did last time, but with emily and that other person volunteering, figured we'd push us to another month. I guess the other person wasn't firm, so now we're 1 short again.

**Comment by bpoetz** [comment]
let me put a call out!

**Comment by rprouse** [comment]
Let me know if you need me. I can do a short talk this month then AJ and I can do the double header.

**Comment by bpoetz** [comment]
thanks Rob! looks like John Fink will be giving a talk - you are welcome to do one this month too if you'd like, but we don't need anyone to take one for the team now :-)

**Comment by rprouse** [comment]
I'll take one for the team next month :smile:

**Pull request merged**
