### PR TITLE
Changed twitter handle

### PR DESCRIPTION
**Pull request by madmurdock**
The existing one was not "ours", and contained retweets that could be bad.

### CODE REVIEW

**Comment by madmurdock** [comment]
Added February event

**Comment by rprouse** [comment]
Looks good, I will have to subscribe to the proper twitter account :smile:

**Comment by rprouse** [comment]
No S16E02?

**Comment by codercampHamOnt** [comment]
I may have screwed that up... I intended to name it that.

That said, how did coding on my phone work out?

**Comment by rprouse** [comment]
I merged the PR, so must have worked out okay. I guess you didn't run the unit tests before checking in?

**Comment by madmurdock** [comment]
Couldn't get the test runner installed on my s3 ;)

**Comment by rprouse** [comment]
What do you mean? Android is built on top of Linux, just drop down to the console, install Node.js and gett'r going! :stuck_out_tongue_winking_eye:

**Pull request merged**
