### PR TITLE
Coder Camp 1

### PR DESCRIPTION
**Pull request by Incognito**
I dug up some ancient emails

### CODE REVIEW

**Comment by rprouse** [comment]
Gotta love some history :+1:

**Comment by rprouse** [comment]
Not sure why this isn't showing up. The changes you made to the other page were fine.

**Comment by Incognito** [comment]
I'm a stranger to Jekyll but there may be some manifest file elsewhere.

**Comment by rprouse** [comment]
I didn't notice in the code review, but it was clearer when I looked locally. You forgot to add the file extension to the new file. Jekyll requires that the files be .md for markdown files. By default, it only compiles .md and .html.

I renamed and pushed the fix to master.

**Pull request merged**
